name: imasync

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build imgsync
      run: make install

    - name: Upload imgsync
      uses: actions/upload-artifact@v1
      with:
        name: imgsync
        path: ${GOPATH}/bin/imgsync

  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: Download imgsync
        uses: actions/download-artifact@v1
        with:
          name: imgsync
          path: /usr/local/bin/imgsync

    - name: Sync k8s.gcr.io
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: imgsync gcr --kubeadm --user ${DOCKER_USER} --password ${DOCKER_PASSWORD}
